// Per-chain native-category → department maps. THE primary categorization
// signal: each chain ships its own taxonomy label on (nearly) every offer, and
// this file maps every label we have seen to one of our 17 departments —
// deterministically, before any keyword guessing. Keyword matching on the
// product name remains only as the fallback for chains that expose no labels
// (masoutis, lidl OCR) and for labels not yet in these maps.
//
// WHY per-chain (not one global alias list): the same word means different
// things at different chains — 'Παιδικά' is kids' suncare at mymarket but baby
// yogurt at kritikos; 'Λευκά' is white wine at mymarket, white cheese at
// kritikos; 'Γάλα' at kritikos is infant formula; 'Συμπυκνωμένα' is fabric
// softener at mymarket, tomato juice at kritikos. A flat map cannot hold those
// truths at once.
//
// Maintenance: when a chain introduces a label that isn't here, the ingest
// report lists it under `unmappedNativeLabels` (surfaced as a run warning in
// the admin Υγεία tab). Add it to the right department and re-run
// recompute-categories.mjs. Keys are matched accent-insensitively after
// lowercase (see normalize() in categories.ts) — write them as the chain emits
// them.
//
// A `null` value means "label is KNOWN but too mixed for one department —
// split it by keywords, and don't report it as unmapped":
// - mymarket 'Μπύρες, Αναψυκτικά, Κρασιά & Ποτά' — beer AND juices together
//   (μπύρα→Κάβα, φρουτοποτό→Πρωινό).
// - ab 'Πρωινό - snacking & ροφήματα' — coffee AND chocolate AND gum in one
//   coarse bucket; keywords route each correctly.
// - kritikos 'Έτοιμα γεύματα' / 'Έτοιμα Γεύματα' / 'Ετοιμα Γεύματα' — three
//   spellings collapse to ONE normalized key but mean canned meals, frozen
//   meals and baby food respectively. Keywords ('κτψ' etc.) split them better
//   than any single mapping could.

const D = {
  fruit: 'Φρούτα & Λαχανικά',
  meat: 'Κρέας & Ψάρι',
  dairy: 'Γαλακτοκομικά & Είδη Ψυγείου',
  cheese: 'Τυριά & Αλλαντικά',
  deli: 'Σαλάτες & Αλοιφές',
  canned: 'Κονσέρβες',
  bakery: 'Αρτοποιία',
  frozen: 'Κατεψυγμένα',
  pantry: 'Είδη Παντοπωλείου',
  breakfast: 'Πρωινό & Ροφήματα',
  snacks: 'Σνακ & Γλυκά',
  drinks: 'Κάβα',
  personal: 'Προσωπική Φροντίδα',
  baby: 'Βρεφικά Είδη',
  home: 'Είδη Καθαρισμού & Σπιτιού',
  pets: 'Είδη Κατοικιδίων',
  other: 'Άλλο',
} as const;

export const CHAIN_NATIVE_MAPS: Record<string, Record<string, string | null>> = {
  mymarket: {
    // Προσωπική Φροντίδα
    'Αφρόλουτρα, Αφροντούς': D.personal,
    'Αποσμητικά': D.personal,
    'Σαμπουάν': D.personal,
    'Βαφές': D.personal,
    'Κρέμες Προσώπου': D.personal,
    'Καθαρισμός Προσώπου': D.personal,
    'Οδοντόκρεμες': D.personal,
    'Λακ, Gel, Αφροί': D.personal,
    'Γαλακτώματα, Κρέμες': D.personal,
    'Σαπούνια, Κρεμοσάπουνα': D.personal,
    'Eνηλίκων': D.personal, // LATIN 'E' — adult suncare line
    'Μαλακτικές Κρέμες Μαλλιών': D.personal,
    'Οδοντόβουρτσες': D.personal,
    'Ξυραφάκια, Μηχανές': D.personal,
    'Σερβιετάκια': D.personal,
    'Σερβιέτες': D.personal,
    'Αποτριχωτικά': D.personal,
    'Λάδια, Serum, Θεραπείες': D.personal,
    'After Shave, Κρέμες Ενυδάτωσης': D.personal,
    'Στοματικά Διαλύματα, Νήματα': D.personal,
    'Μάσκες': D.personal,
    'Αντιβακτηριδιακά': D.personal,
    'Πάνες Εσώρουχα Ακράτειας': D.personal,
    'Επιθέματα Ελαφράς Ακράτειας': D.personal,
    'Αρώματα': D.personal,
    'Προσώπου': D.personal,
    'Παιδικά': D.personal, // kids' suncare (Nivea Sun Children) — NOT toys
    'Αφροί, Gel': D.personal,
    'Ηλεκτρικές  Οδοντόβουρτσες': D.personal,
    'Ταμπόν': D.personal,
    'Ανταλλακτικά': D.personal, // razor refills
    'Dry Shampoo': D.personal,
    'Προφυλακτικά': D.personal,
    'Ανοιχτές Πάνες Ακράτειας': D.personal,
    'Περιποίηση Ποδιών, Χεριών': D.personal,
    'Βαμβάκι, Μπατονέτες': D.personal,
    'Μάσκες Προστασίας Προσώπου': D.personal,
    'Προιόντα Αδυνατίσματος': D.personal,
    'Μακιγιάζ': D.personal,
    'Υποσέντονα Ενηλίκων': D.personal,
    'Τεχνητή Οδοντοστοιχία': D.personal,
    'Καθαρισμός Ευαίσθητης Περιοχής': D.personal,
    // Βρεφικά Είδη
    'Φροντίδα για το Μωρό σας': D.baby,
    'Pants': D.baby, // Pampers (at kritikos the same word is TENA adult!)
    'Περιποίηση Σώματος Βρέφους': D.baby,
    'Βρεφικές Κρέμες': D.baby,
    'Premium Care': D.baby,
    'Φροντίδα Μαλλιών Βρέφους': D.baby,
    'Γευματάκια': D.baby,
    'Septona': D.baby,
    'Babycare': D.baby,
    "Calm N' Care": D.baby,
    'Premium Care Pants': D.baby,
    'Active Baby': D.baby,
    'Splashers': D.baby,
    'Safe Nights': D.baby,
    'Feel Good!, Pappy': D.baby,
    'Sensitive': D.baby,
    "Calm N' Care Pants": D.baby,
    'Swim Pants': D.baby,
    'Babylino': D.baby,
    'Στοματική Υγιεινή Βρεφών': D.baby,
    // Είδη Καθαρισμού & Σπιτιού
    'Υγρό': D.home,
    'Για το Μπάνιο': D.home,
    'Υγρά Πιάτων': D.home,
    'Πατώματος, Παρκέ': D.home,
    'Γενικής Χρήσης': D.home,
    'Ενισχυτικά Πλύσης, Σιδέρωμα': D.home,
    'Απορρυπαντικά Πλυντηρίου Πιάτων': D.home,
    'Εντομοαπωθητικά': D.home,
    'Υγρά Μαλακτικά': D.home,
    'Οικιακή Φροντίδα & Χαρτικά': D.home,
    'Συμπυκνωμένα': D.home, // Soupline softener (kritikos same word = tomato juice!)
    'Εντομοκτόνα': D.home,
    'Εργαλεία Κουζίνας': D.home,
    'Σφουγγάρια, Σπογγοπετσέτες': D.home,
    'Υγείας': D.home, // χαρτί υγείας
    'Λευκά Είδη': D.home, // pillows/linens
    'Σκούπες, Σφουγγαρίστρες, Κουβάδες': D.home,
    'Αρωματικά Χώρου, Κεριά': D.home,
    'Χλωρίνες, Πολυκαθαριστικά': D.home,
    'Χαρτομάντηλα': D.home,
    'Τζάμια': D.home,
    'Σκόνη': D.home,
    'Φύλαξη Ρούχων': D.home,
    'Κουζίνας': D.home, // ρολό κουζίνας
    'Μπαταρίες': D.home,
    'Αλουμινόχαρτο, Μεμβράνες': D.home,
    'Κάψουλες, Ταμπλέτες': D.home, // laundry pods
    'Κουζίνας, Λιποκαθαριστές': D.home,
    'Αποσκληρυντικό': D.home,
    'Χαρτοπετσέτες': D.home,
    'Έτοιμες Συνταγές': D.pantry,
    'Σκεύη Μαγειρικής': D.home,
    'Σακούλες Απορριμμάτων': D.home,
    'Σκοροκτόνα': D.home,
    'Ξεσκόνισμα, Καθάρισμα Επίπλων': D.home,
    'Απορρυπαντικά Βρεφικά': D.home,
    'Μπάνιο': D.home,
    'Είδη Σερβιρίσματος': D.home,
    'Είδη Μιας Χρήσης': D.home,
    'Κατά των Αλάτων': D.home,
    'Γάντια': D.home,
    'Αρωματικά Ρούχων': D.home,
    'Κουζίνα, Μικροσυσκευές & Σπίτι': D.home,
    'Είδη Ταξιδίου': D.home,
    'Σφουγγαράκια, Συρματάκια': D.home,
    'Συλλέκτες Υγρασίας': D.home,
    'Καμινέτα': D.home,
    'Χαλιά': D.home,
    'Υλικά Χειροτεχνίας': D.home,
    'Υγρά Μαντηλάκια': D.home, // Zewa moist toilet paper
    'Σακούλες Τροφίμων': D.home,
    'Ηλεκτρικές Συσκευές': D.home,
    'Σιδέρωμα, Άπλωμα': D.home,
    'Για την Παραλία': D.home,
    'Πλύσιμο Στο Χέρι': D.home,
    'Αποφρακτικά': D.home,
    // Είδη Κατοικιδίων
    'Υγρή Τροφή': D.pets,
    'Ξηρή Τροφή': D.pets,
    'Μπισκότα, Σνακ': D.pets, // Pedigree dog biscuits
    'Αξεσουάρ': D.pets,
    'Φροντίδα για το Κατοικίδιο σας': D.pets,
    'Τροφές': D.pets,
    // Κάβα
    'Energy Drinks': D.drinks,
    'Lager': D.drinks,
    'Pils': D.drinks,
    'Διάφορες Γεύσεις': D.drinks, // Βίκος/Xixo flavored sodas
    'Ready To Drink': D.drinks,
    'Λευκά': D.drinks, // white WINE here (kritikos same word = white cheese!)
    'Χωρίς Αλκοόλ': D.drinks,
    'Cola': D.drinks,
    'Ροζέ': D.drinks,
    'Whisky': D.drinks,
    'Ερυθρά': D.drinks,
    'Πορτοκαλάδα': D.drinks,
    'Σόδα, Τόνικ': D.drinks,
    'Γκαζόζα': D.drinks,
    'Τσίπουρο, Ρακί': D.drinks,
    'Rum': D.drinks,
    'Αφρώδη': D.drinks,
    'Ούζο': D.drinks,
    'Ανθρακούχα Νερά': D.drinks,
    'Λεμονάδα': D.drinks,
    'Gin': D.drinks,
    'Μηλίτης': D.drinks,
    'Tequila': D.drinks,
    'Liqueur, Aperitif': D.drinks,
    'Vodka': D.drinks,
    'Ale': D.drinks,
    'Μη Αλκοολούχα': D.drinks,
    'Weiss': D.drinks,
    'Stout': D.drinks,
    'Μοναστηριακές': D.drinks,
    'Φυσικά Μεταλλικά, Επιτραπέζια Νερά': D.drinks,
    'Βιταμινούχα Νερά': D.drinks,
    // Πρωινό & Ροφήματα
    'Χυμοί': D.breakfast,
    'Χυμοί, Τσάι': D.breakfast,
    'Δημητριακά Ενηλίκων': D.breakfast,
    'Κάψουλες': D.breakfast,
    'Κρύο Τσάι': D.breakfast,
    'Espresso': D.breakfast,
    'Πρωινό, Ροφήματα & Καφές': D.breakfast,
    'Muesli, Βρώμη': D.breakfast,
    'Παιδικά, Εφηβικά Δημητριακά': D.breakfast,
    'Μέλι': D.breakfast,
    'Μαρμελάδες': D.breakfast,
    'Τσάι': D.breakfast,
    'Ελληνικός': D.breakfast,
    'Στιγμιαίος Καφές': D.breakfast,
    'Φίλτρου': D.breakfast,
    'Ταχίνι': D.breakfast,
    'Για παιδιά': D.breakfast, // cocoa drinks
    'Ροφήματα': D.breakfast,
    'Κακάο': D.breakfast,
    'Ενηλίκων': D.breakfast, // GREEK Ε — Mokate chocolate drinks
    // Γαλακτοκομικά & Είδη Ψυγείου
    'Επιδόρπια Γιαουρτιού': D.dairy,
    'Στραγγιστό': D.dairy,
    'Βούτυρο': D.dairy,
    'Κρέμες Γάλακτος': D.dairy,
    'Μαργαρίνη': D.dairy,
    'Υψηλής Παστερίωσης': D.dairy,
    'Σοκολατούχο': D.dairy,
    'Αυγά': D.dairy,
    'Κρέμες': D.dairy, // Στάμου/Γιώτης dairy dessert creams
    'Παιδικό': D.dairy, // Κρι Κρι babies yogurt
    'Διάφορα Επιδόρπια': D.dairy,
    'Πρόβειο': D.dairy,
    'Φρέσκο': D.dairy,
    'Αγελάδος': D.dairy,
    'Ρυζόγαλο': D.dairy,
    'Εβαπορέ': D.dairy,
    'Κατσικίσιο': D.dairy,
    'Φρέσκες Ζύμες': D.dairy,
    'Μη Γαλακτοκομικά Προϊόντα': D.cheese,
    'Μη Γαλακτοκομικά επιδόρπια , Φυτικές Κρέμες': D.dairy,
    // Τυριά & Αλλαντικά
    'Σε Φέτες': D.cheese,
    'Τριμμένα': D.cheese,
    'Γραβιέρα, Κεφαλοτύρι': D.cheese,
    'Φέτα, Λευκά Τυριά': D.cheese,
    'Κρεμώδη, Αλειφόμενα': D.cheese,
    'Γαλοπούλα, Κοτόπουλο': D.cheese, // deli slices
    'Μίνι, Μερίδες': D.cheese,
    'Λουκάνικα': D.cheese,
    'Mozzarella, Χαλούμι': D.cheese,
    'Κασέρι, Κίτρινα Τυριά': D.cheese,
    'Πάριζα, Παριζάκι': D.cheese,
    'Τυριά, Αλλαντικά & Deli': D.cheese,
    'Κρεατικά, Λουκάνικα': D.cheese,
    'Combi Αλλαντικό Και Τυρί': D.cheese,
    'Ζαμπόν': D.cheese,
    'Μπέικον': D.cheese,
    'Σαλάμια': D.cheese,
    'Προσούτο': D.cheese,
    'Υποκατάστατα τυροκομικών': D.cheese,
    'Gouda, Emmental, Edam, Cheddar': D.cheese,
    'Παρμεζάνα, Regato': D.cheese,
    // Κρέας & Ψάρι
    'Θαλασσινά, Όστρακα': D.meat,
    'Ψάρια': D.meat,
    'Κρέας': D.meat,
    'Κοτόπουλο': D.meat,
    'Μοσχάρι': D.meat,
    'Χοιρινό': D.meat,
    'Παστά': D.meat,
    // Σαλάτες & Αλοιφές
    'Σαλάτες': D.deli,
    'Έτοιμες Σαλάτες': D.fruit, // fresh bagged salad leaves
    // Κονσέρβες
    'Τοματοειδή': D.canned,
    'Τόνος, Σαρδέλες': D.canned,
    'Μανιτάρια, Λαχανικά': D.canned, // jarred peppers/capers
    'Ψάρια, Θαλασσινά': D.canned, // Trata pocket canned
    // Κατεψυγμένα
    'Παγωτά': D.frozen,
    'Πίτες, Πίτσες, Πεϊνιρλί': D.frozen,
    'Έτοιμα Φαγητά': D.frozen, // Μπάρμπα Στάθης ready frozen
    'Κατεψυγμένα Τρόφιμα': D.frozen,
    'Λαχανικά': D.frozen, // Μπ. Στάθης frozen vegetables here
    'Υποκατάστατα Κρέατος': D.frozen,
    'Φύλλα': D.frozen,
    'Πατάτες': D.frozen, // Mc Cain
    'Ζύμες': D.frozen,
    'Λαχανικά, Φρούτα': D.frozen, // sample: frozen spinach
    // Αρτοποιία
    'Παξιμάδια': D.bakery,
    'Ψωμί Του Τοστ': D.bakery,
    'Κριτσίνια': D.bakery,
    'Ψωμάκια, Πίτες, Πεϊνιρλί': D.bakery,
    'Αρτοσκευάσματα': D.bakery,
    'Ψωμί': D.bakery,
    'Ο Φούρνος μας': D.bakery,
    'Φρυγανιές': D.bakery,
    'Τσουρέκια': D.bakery,
    'Τρίμμα  Φρυγανιάς': D.bakery,
    // Σνακ & Γλυκά
    'Γεμιστά': D.snacks,
    'Καραμέλες': D.snacks,
    'Μπάρες': D.snacks,
    'Γκοφρέτες, Μπάρες': D.snacks,
    'Σοκολάτες': D.snacks,
    'Κράκερς': D.snacks,
    'Πατατάκια': D.snacks,
    'Αρτοζαχαροπλαστείο & Snacks': D.snacks,
    'Σοκολατάκια, Minis': D.snacks,
    'Κρουασάν, Λουκουμάδες': D.snacks,
    'Ξηροί Καρποί': D.snacks,
    'Τσίχλες': D.snacks,
    'Κρέμες Στιγμής, Ζελέ': D.snacks,
    'Απλά': D.snacks, // Παπαδοπούλου plain biscuits (kritikos same word = eggs!)
    'Γλυκά': D.snacks,
    'Χαλβάς, Παστέλια, Μαντολάτα': D.snacks,
    'Πραλίνα': D.snacks,
    'Σοκολάτα': D.snacks,
    'Nachos': D.snacks,
    'Πολυδημητριακά': D.snacks,
    'Υγιεινά': D.snacks,
    'Λοιπά': D.snacks,
    'Κουβερτούρες': D.snacks,
    'Αλμυρά': D.snacks,
    'Παραδοσιακά  Γλυκά': D.snacks,
    'Κέικ': D.snacks,
    'Digestive': D.snacks,
    'Ζελέ': D.snacks,
    'Εποχιακά, Λοιπά Σοκολατοειδή': D.snacks,
    'Sweet & Balance': D.snacks,
    'Φυστικοβούτυρο': D.snacks,
    'Bites': D.snacks,
    'Κρουτόν': D.snacks,
    // Είδη Παντοπωλείου
    'Άλλες Πάστες': D.pantry,
    'Ελαιόλαδο': D.pantry,
    'Διεθνής Κουζίνα': D.pantry,
    'Μακαρόνια': D.pantry,
    'Μαγιονέζα': D.pantry,
    'Τρόφιμα': D.pantry,
    'Κέτσαπ': D.pantry,
    'Για Κρέας': D.pantry,
    'Ρύζι': D.pantry,
    'Για Ζυμαρικά': D.pantry,
    'Κύβοι, Ζωμοί': D.pantry,
    'Μουστάρδα': D.pantry,
    'Ξύδι': D.pantry,
    'Γλυκαντικά': D.pantry,
    'Κριθαράκι': D.pantry,
    'Σπορέλαιο': D.pantry,
    'Ελιές': D.pantry,
    'Αλάτι': D.pantry,
    'Μαγειρικά Λίπη': D.pantry,
    'Μείγματα Για Γλυκά': D.pantry,
    'Αλεύρι': D.pantry,
    'Πουρές': D.pantry,
    'Μπαχαρικά': D.pantry,
    'Φασόλια': D.pantry,
    'Φακές': D.pantry,
    'Για Σαλάτες': D.pantry,
    'Παραδοσιακά': D.pantry, // χυλοπίτες (kritikos same word = yogurt!)
    'Ζωμοί Ψυγείου': D.pantry,
    'Superfoods': D.pantry,
    'Ζάχαρη Καστανή & Μαύρη': D.pantry,
    'Σιμιγδάλι': D.pantry,
    'Μπεσαμέλ': D.pantry,
    'Φάβα, Ρεβύθια': D.pantry,
    'Σόγια': D.pantry,
    'Ζάχαρη Άχνη': D.pantry,
    'Ζάχαρη': D.pantry,
    'Μείγματα Μπαχαρικών': D.pantry,
    'Παντεσπάνι, Βάσεις': D.pantry,
    'Ψάρι': D.pantry, // 'for fish' sauces (sample: Hellmann's Tartar)
    // Φρούτα & Λαχανικά (real produce)
    'Τομάτες, Τοματίνια, Αγγούρια': D.fruit,
    'Μανιτάρια, Καλαμπόκι, Αγκινάρες, Σπαράγγια': D.fruit,
    // Άλλο (genuinely non-grocery)
    'Τετράδια, Μπλοκ, Χαρτί': D.other,
    'Παιχνίδια': D.other,
    'Ένδυση, Εσώρουχα': D.other,
    // Known-but-mixed → keyword split (see header comment)
    'Μπύρες, Αναψυκτικά, Κρασιά & Ποτά': null,
  },

  kritikos: {
    // Προσωπική Φροντίδα
    'Αφρόλουτρα': D.personal,
    'Αποσμητικά Σώματος': D.personal,
    'Σαμπουάν': D.personal,
    'Βαφές': D.personal,
    'Οδοντόκρεμες': D.personal,
    'Γαλάκτωμα': D.personal,
    'Καθαρισμός': D.personal, // Garnier micellar
    'Κρέμες': D.personal, // Nivea face/hand (mymarket same word = dairy creams!)
    'Κρεμοσάπουνα': D.personal,
    'Conditioner': D.personal,
    'Λάδι / Μάσκα': D.personal,
    'Σερβιέτες': D.personal,
    'Σερβιετάκια': D.personal,
    'Λάδι': D.personal, // Ambre Solaire suncare oil
    'Ακράτειας': D.personal,
    'Body Milk / Lotions': D.personal,
    'Pants': D.personal, // TENA adult pants (mymarket same word = Pampers!)
    'Σαμπουάν / Αφρόλουτρα': D.personal,
    'Hair Spray': D.personal,
    'Οδοντόβουρτσες': D.personal,
    'Υγρά Μαντηλάκια': D.personal, // Hankies
    'Αφρός - Gel': D.personal,
    'Gel': D.personal,
    'Αποτριχωτικά': D.personal,
    'Στοματικό Διάλυμα': D.personal,
    'Κρέμες Χεριών': D.personal,
    'Ηλεκτρικές Οδοντόβουρτσες': D.personal,
    'Παιδικές Οδοντόκρεμες': D.personal,
    'Μιας Χρήσης': D.personal, // Gillette disposables
    'Αφρός': D.personal,
    'Παιδικές Οδοντόβουρτσες': D.personal,
    'Ταμπόν': D.personal,
    'Ανταλλακτικά': D.personal,
    'Εμπλαστρα - Θερμοφόρες': D.personal,
    'Βαμβάκι': D.personal,
    'Κερί - Πηλός': D.personal,
    'Οδοντικό Νήμα': D.personal,
    'Μηχανές': D.personal,
    'Υποσέντονα': D.personal,
    'Προφυλακτικά': D.personal,
    // Βρεφικά Είδη
    'Ανοιχτές Πάνες': D.baby,
    'Multipack': D.baby,
    'Πάνες Βρακάκια': D.baby,
    'Μονά': D.baby,
    'Κρέμες Σε Σκόνη': D.baby,
    'Γάλα': D.baby, // Almiron infant formula!
    'Κρέμα / Λοσιόν': D.baby,
    'Λάδι / Πούδρα': D.baby, // Johnson's Baby oil
    // Είδη Καθαρισμού & Σπιτιού
    'Μαλακτικά': D.home,
    'Υγρά Πιάτων': D.home,
    'Υγρό Πλυντηρίου': D.home,
    'Υγρά Δαπέδου': D.home,
    'Ταμπλέτες': D.home,
    'Απολυμαντικά': D.home,
    'Μπάνιου': D.home,
    'Ενισχυτικά - Χρωμοπαγιδες': D.home,
    'WC Block': D.home,
    'Υγρά Ταμπλέτες': D.home,
    'Σκόνη Πλυντηρίου': D.home,
    'Χαρτιά Υγείας': D.home,
    'Κουζίνας': D.home,
    'Κατσαριδοκτόνα': D.home,
    'Γενικής Χρήσης': D.home,
    'Εντομ/Τικα / Λοσιόν': D.home,
    'Χαρτομάντηλα': D.home,
    'Σακούλες Σκουπιδιών': D.home,
    'Πανιά Καθαρισμού': D.home,
    'Σφουγγάρια Κουζίνας & Μπάνιου': D.home,
    'Σκοροκτόνα': D.home,
    'Αλάτι - Καθαριστικά': D.home,
    'Σύρματα': D.home,
    'Σπογγοπετσέτες': D.home,
    'Μεμβράνες - Αλουμινόχαρτο - Δοχεία': D.home,
    'Μπαταρίες': D.home,
    'Σφουγγαρίστρες': D.home,
    'Spray': D.home,
    'Απορ/κα Πλυντηρίου': D.home,
    'Αποσκληρυντικά': D.home,
    'Χλωρίνες': D.home,
    'Τζαμιών': D.home,
    'Κουβάδες': D.home,
    'Σπιράλ / Κεριά': D.home,
    'Παγίδες': D.home,
    // Είδη Κατοικιδίων
    'Υγρή Τροφή': D.pets,
    'Αξεσουάρ': D.pets,
    'Υγιεινή': D.pets, // cat litter!
    // Κάβα
    'Ενεργειακά': D.drinks,
    'Cola': D.drinks,
    'Lager': D.drinks,
    'Pils': D.drinks,
    'Διάφορες Γεύσεις': D.drinks,
    'Πορτοκαλάδα': D.drinks,
    'Alcohol Free': D.drinks,
    'Γκαζόζα': D.drinks,
    'Ερυθρά': D.drinks,
    'Τεκίλα': D.drinks,
    'Ούζο': D.drinks,
    'Μεταλλικό': D.drinks,
    'Λεμονάδα': D.drinks,
    'Weiss': D.drinks,
    'Dark': D.drinks,
    'Ροζέ': D.drinks,
    'Γλυκά': D.drinks, // sweet WINES here (mymarket same word = pastries!)
    'Τσίπουρο': D.drinks,
    'Gin': D.drinks,
    'Ουίσκι': D.drinks,
    'Βότκα': D.drinks,
    'Λικέρ': D.drinks,
    // Πρωινό & Ροφήματα
    'Χυμοί Ψυγείου': D.breakfast,
    'Παιδικά Δημητριακά': D.breakfast,
    'Δημητριακά': D.breakfast,
    'Ταχίνι': D.breakfast,
    'Κάψουλες': D.breakfast,
    'Ελληνικός': D.breakfast,
    'Τσάι': D.breakfast,
    'Ice Tea': D.breakfast,
    'Μαρμελάδες': D.breakfast,
    'Στιγμιαίος': D.breakfast,
    'Espresso': D.breakfast,
    'Κακάο - Σοκολατούχα Ροφήματα': D.breakfast,
    'Φυσικοί': D.breakfast,
    'Φρουτοποτά': D.breakfast,
    'Νέκταρ': D.breakfast,
    'Φίλτρου': D.breakfast,
    // Γαλακτοκομικά & Είδη Ψυγείου
    'Ενηλίκων': D.dairy, // GREEK Ε — dessert cream cups
    'Φυτικά Ροφήματα': D.dairy,
    'Παιδικά': D.dairy, // Κρι Κρι babies yogurt (mymarket same word = kids suncare!)
    'Λειτουργικά': D.dairy,
    'Βούτυρα / Μαργαρίνες': D.dairy,
    'Στραγγιστά': D.dairy,
    'Παραδοσιακά': D.dairy, // yogurt (mymarket same word = χυλοπίτες!)
    'Ροφήματα Με Βάση Γάλα': D.dairy,
    'Σοκολατούχο': D.dairy,
    'Φυτικά Επιδόρπια': D.dairy,
    'Απλά': D.dairy, // EGGS here (mymarket same word = plain biscuits!)
    'Επιδόρπια Με Φρούτα': D.dairy,
    'Υψηλής Παστερίωσης': D.dairy,
    'Φρέσκο': D.dairy,
    'Αγελαδινά': D.dairy,
    'Βιολογικά - Ειδικά': D.dairy, // eggs
    'Ζύμες': D.dairy, // ΚΑΝΑΚΙ fresh dough
    'Βούτυρα': D.dairy,
    // Τυριά & Αλλαντικά
    'Κασέρι - Gouda - Edam - Emmental': D.cheese,
    'Λευκά': D.cheese, // white CHEESE here (mymarket same word = white wine!)
    'Light': D.cheese,
    'Γραβιέρα - Κεφαλοτύρι': D.cheese,
    'Κρεμώδη': D.cheese,
    'Γαλοπούλα': D.cheese,
    'Φέτα': D.cheese,
    'Παιδικά - Τρίγωνα': D.cheese,
    'Λουκάνικα Συσκευασμένα': D.cheese,
    'Κοτόπουλο': D.cheese, // deli roast chicken slices
    'Πάριζα / Παριζάκι': D.cheese,
    'Ζαμπόν': D.cheese,
    'Μπέικον': D.cheese,
    'Delicatessen': D.cheese,
    'Σαλάμι': D.cheese,
    'Φυτικά Αναπληρώματα': D.cheese,
    // Κρέας & Ψάρι
    'Κοτόπουλο / Γαλοπούλα': D.meat,
    'Χοιρινό': D.meat,
    'Μοσχάρι': D.meat,
    'Παρασκευάσματα Κρέατος': D.meat,
    'Ψάρια': D.meat,
    'Χταπόδι - Καλαμάρι - Σουπιά': D.meat,
    'Γαρίδες - Όστρακα': D.meat,
    // Σαλάτες & Αλοιφές
    'Σαλάτες': D.deli,
    'Έτοιμες Σαλάτες': D.fruit, // fresh bagged salad
    // Κονσέρβες
    'Τόνος': D.canned,
    'Ψιλοκομμένα': D.canned,
    'Συμπυκνωμένα': D.canned, // tomato juice (mymarket same word = softener!)
    'Πελτές': D.canned,
    'Τοματικά': D.canned,
    // Κατεψυγμένα
    'Παγωτά': D.frozen,
    'Ανάμικτα Λαχανικά': D.frozen,
    'Πίτες - Πιτάκια': D.frozen,
    'Διάφορα': D.frozen, // Μπ. Στάθης ΚΤΨ
    'Φασολάκια': D.frozen,
    'Λαχανικά Κατεψυγμένα': D.frozen,
    'Αρακάς': D.frozen,
    'Πατάτες': D.frozen,
    'Έτοιμα Γεύματα Φυτικά': D.frozen,
    'Πίτσες - Πεινιρλί': D.frozen,
    'Έτοιμα Γεύματα Λαχανικά': D.frozen,
    'Παναρισμένα': D.frozen,
    'Αγγινάρες': D.frozen,
    // Αρτοποιία
    'Τοστ Σταρένιο': D.bakery,
    'Τοστ Ολικής': D.bakery,
    'Τοστ Σίκαλης': D.bakery,
    'Παξιμάδια': D.bakery,
    'Κριτσίνια': D.bakery,
    'Πίτες /Wrap /Αραβικές': D.bakery,
    'Λοιπά Είδη Ψωμιού': D.bakery,
    'Λοιπά Είδη Φρυγανιών': D.bakery,
    'Σταρένιες': D.bakery,
    'Σίκαλης': D.bakery,
    'Burger': D.bakery, // Κρις Κρις sandwich bread
    // Σνακ & Γλυκά
    'Μπάρες Δημητριακών': D.snacks,
    'Τσιπς': D.snacks,
    'Γκοφρέτες & Snacks': D.snacks,
    'Πραλίνα / Φυστικοβούτυρο / Spreads': D.snacks,
    'Γεμιστά': D.snacks,
    'Πολυδημητριακά': D.snacks,
    'Φρουί Ζελέ': D.snacks,
    'Αλμυρά Σνακ': D.snacks,
    'Nachos': D.snacks,
    'Σοκολατάκια': D.snacks,
    'Mini': D.snacks,
    'Γεμιστές': D.snacks,
    'Του κουταλιού / Διάφορα': D.snacks,
    'Κράκερς': D.snacks,
    'Γαριδάκια': D.snacks,
    'Κέικ': D.snacks,
    'Τσίχλες': D.snacks,
    'Γάλακτος': D.snacks, // CRUNCH milk chocolate!
    'Διάφοροι Χαλβάδες': D.snacks,
    'Κρουασάν': D.snacks,
    'Λεύκες': D.snacks, // white-chocolate label typo
    'Παστέλια': D.snacks,
    'Βουτήματα': D.snacks,
    // Είδη Παντοπωλείου
    'Μακαρόνια': D.pantry,
    'Ανατολίτικη Κουζίνα': D.pantry,
    'Πένες - Ριγκατόνι - Κανελόνια': D.pantry,
    'Κέτσαπ': D.pantry,
    'Για Ζυμαρικά': D.pantry,
    'Μαγιονέζα': D.pantry,
    'Ολικής': D.pantry,
    'Ελαιόλαδο Έξτρα Παρθένο': D.pantry,
    'Ελαιόλαδο Κλασσικό': D.pantry,
    'Έτοιμα Φαγητά': D.pantry, // Knorr snack pots
    'Μουστάρδα': D.pantry,
    'Για BBQ': D.pantry,
    'Ηλιέλαιο': D.pantry,
    'Κοφτό - Κριθαράκι - Φιογκάκι': D.pantry,
    'Έτοιμα Μείγματα': D.pantry,
    'Πουρές': D.pantry,
    'Κίτρινο': D.pantry, // parboiled rice!
    'Για κρέας / Ψάρι': D.pantry,
    'Αραβοσιτέλαιο': D.pantry,
    'Ζωμοί Ψυγείου': D.pantry,
    'Έτοιμα Μιξ': D.pantry,
    'Για Όλες Τις Χρήσεις': D.pantry,
    'Χωρίς Γλουτένη': D.pantry,
    'Για Σαλάτες': D.pantry,
    'Δυτική Κουζίνα': D.pantry,
    'Αλάτι': D.pantry,
    'Ετοιμες Συνταγές': D.pantry,
    'Καστανό': D.pantry,
    'Καρολίνα': D.pantry,
    'Γλασέ': D.pantry,
    'Αγριο': D.pantry,
    'Μπασμάτι': D.pantry,
    'Πυρηνέλαιο': D.pantry,
    'Λευκό': D.pantry, // white vinegar
    'Κόκκινο': D.pantry, // red vinegar
    'Κότας': D.pantry, // Maggi stock
    'Λαχανικών': D.pantry, // Maggi stock
    'Βοδινό': D.pantry, // Maggi stock (global alias said meat — chain truth wins)
    'Διάφορες Συνταγές': D.pantry,
    'Φακές': D.pantry,
    'Φάβα': D.pantry,
    'Φασόλια': D.pantry,
    'Ελιές Συσκευασμένες': D.pantry,
    'Αλεύρι': D.pantry,
    'Ολικής Αλεσης': D.pantry,
    'Μπαχαρικά': D.pantry,
    'Ζυμαρικά': D.pantry,
    'Οσπρια': D.pantry,
    'Superfoods': D.pantry,
    // Φρούτα & Λαχανικά (real produce!)
    'Λαχανικά': D.fruit, // ΑΓΓΟΥΡΙΑ, ΤΟΜΑΤΕΣ fresh (mymarket same word = frozen!)
    'Φρούτα': D.fruit,
  },

  // sklavenitis labels are URL slug pairs ("seg1/seg2") emitted raw by the
  // adapter — the chain RENAMED its taxonomy once already (the adapter's old
  // hardcoded slug map went stale silently and items fell to keyword guessing;
  // that's how frozen Μπάρμπα Στάθης reached Φρούτα). Unknown slugs now warn.
  sklavenitis: {
    'allantika/allantika-galopoylas-kotopoyloy': D.cheese,
    'allantika/loykanika': D.cheese,
    'allantika/paradosiaka-allantika': D.cheese,
    'allantika/pariza-mortadela': D.cheese,
    'allantika/salamia': D.cheese,
    'allantika/set-allantikon-tyrion': D.cheese,
    'allantika/zampon-mpeikon-omoplati': D.cheese,
    'anapsyktika-nera-chymoi/anapsyktika-sodes-energeiaka-pota': D.drinks,
    'anapsyktika-nera-chymoi/chymoi': D.breakfast,
    'anapsyktika-nera-chymoi/nera': D.drinks,
    'aporrypantika-eidi-katharismoy/aporrypantika-piaton': D.home,
    'aporrypantika-eidi-katharismoy/aporrypantika-roychon': D.home,
    'aporrypantika-eidi-katharismoy/katharistika-genikis-chrisis': D.home,
    'aporrypantika-eidi-katharismoy/synerga-katharismoy': D.home,
    'ayga-voytyro-nopes-zymes-zomoi/ayga': D.dairy,
    'ayga-voytyro-nopes-zymes-zomoi/freska-zymarika-saltses': D.dairy,
    'ayga-voytyro-nopes-zymes-zomoi/margarines': D.dairy,
    'ayga-voytyro-nopes-zymes-zomoi/voytyra': D.dairy,
    'ayga-voytyro-nopes-zymes-zomoi/zymes-nopes': D.dairy,
    'chartika-panes-servietes/chartika': D.home,
    'chartika-panes-servietes/servietes-panes-enilikon': D.personal,
    'chartika-panes-servietes/vrefikes-paidikes-panes-moromantila': D.baby,
    'eidi-artozacharoplasteioy/keik-tsoyrekia-kroyasan': D.snacks,
    'eidi-artozacharoplasteioy/koyloyria-voytimata': D.snacks,
    'eidi-artozacharoplasteioy/kritsinia-paximadia-fryganies': D.bakery,
    'eidi-artozacharoplasteioy/pites-tortigies': D.bakery,
    'eidi-artozacharoplasteioy/psomi-artoskeyasmata': D.bakery,
    'eidi-artozacharoplasteioy/psomi-typopoiimeno': D.bakery,
    'eidi-mias-chrisis-eidi-parti/eidi-parti': D.home,
    'eidi-mias-chrisis-eidi-parti/eidi-syntirisis-psisimatos-trofimon': D.home,
    'eidi-mias-chrisis-eidi-parti/sakoyles-aporrimmaton': D.home,
    'eidi-mias-chrisis-eidi-parti/servitsia-mias-chrisis': D.home,
    'eidi-oikiakis-chrisis/aromatika-horou-sullektes-ugrasias-filtra-aporrofitira': D.home,
    'eidi-oikiakis-chrisis/eidi-ugraeriou-anaptires-spirta': D.home,
    'eidi-oikiakis-chrisis/entomoapothitika-entomoktona': D.home,
    'eidi-oikiakis-chrisis/fylaxi-peripoiisi-roychon': D.home,
    'eidi-proinoy-rofimata/dimitriaka-mpares': D.breakfast,
    'eidi-proinoy-rofimata/galata-fytika-rofimata-makras-diarkeias': D.dairy,
    'eidi-proinoy-rofimata/kafedes-rofimata-afepsimata': D.breakfast,
    'eidi-proinoy-rofimata/melia-marmelades': D.breakfast,
    'eidi-proinoy-rofimata/pralines-tachini-fystikovoytyro': D.snacks,
    'freska-froyta-lachanika/froyta': D.fruit,
    'freska-froyta-lachanika/kommena-lahanika': D.fruit,
    'freska-froyta-lachanika/lachanika': D.fruit,
    'fresko-kreas/freska-paraskeyasmata-kreaton-poylerikon': D.meat,
    'fresko-kreas/freska-poylerika': D.meat,
    'fresko-kreas/fresko-choirino': D.meat,
    'fresko-kreas/fresko-moschari': D.meat,
    'fresko-psari-thalassina/psaria-ichthyokalliergeias': D.meat,
    'galata-rofimata-chymoi-psygeioy/chymoi-tsai-psygeioy': D.breakfast,
    'galata-rofimata-chymoi-psygeioy/futika-alla-rofimata-psugeiou': D.dairy,
    'galata-rofimata-chymoi-psygeioy/galata-psygeioy': D.dairy,
    'galata-rofimata-chymoi-psygeioy/galata-sokolatoycha-psygeioy': D.dairy,
    'giaoyrtia-kremes-galaktos-epidorpia-psygeioy/epidorpia-giaoyrtioy': D.dairy,
    'giaoyrtia-kremes-galaktos-epidorpia-psygeioy/fytika-epidorpia': D.dairy,
    'giaoyrtia-kremes-galaktos-epidorpia-psygeioy/giaoyrtia': D.dairy,
    'giaoyrtia-kremes-galaktos-epidorpia-psygeioy/giaoyrtia-vrefika-paidika': D.dairy,
    'giaoyrtia-kremes-galaktos-epidorpia-psygeioy/kremes-galaktos-santigi': D.dairy,
    'giaoyrtia-kremes-galaktos-epidorpia-psygeioy/proteinouha-giaoyrtia-epidorpia-glykismata-psygeiou': D.dairy,
    'giaoyrtia-kremes-galaktos-epidorpia-psygeioy/ryzogala-glykismata-psygeioy': D.dairy,
    'kallyntika-eidi-prosopikis-ygieinis/antiliaka': D.personal,
    'kallyntika-eidi-prosopikis-ygieinis/eidi-xyrismatos-after-shave': D.personal,
    'kallyntika-eidi-prosopikis-ygieinis/frontida-mallion': D.personal,
    'kallyntika-eidi-prosopikis-ygieinis/frontida-somatos': D.personal,
    'kallyntika-eidi-prosopikis-ygieinis/parafarmakeytika-eidi': D.personal,
    'kallyntika-eidi-prosopikis-ygieinis/stomatiki-ygieini': D.personal,
    'kallyntika-eidi-prosopikis-ygieinis/vrefika-paidika-kallyntika': D.baby,
    'kallyntika-eidi-prosopikis-ygieinis/ygieini-peripoiisi-prosopoy': D.personal,
    'katepsygmena/katepsygmena-fytika-anapliromata': D.frozen,
    'katepsygmena/katepsygmena-geymata': D.frozen,
    'katepsygmena/katepsygmena-kreata-poylerika': D.frozen,
    'katepsygmena/katepsygmena-lachanika-froyta': D.frozen,
    'katepsygmena/katepsygmena-psaria-thalassina': D.frozen,
    'katepsygmena/katepsygmenes-zymes-pites-pitses': D.frozen,
    'katepsygmena/pagota-pagakia': D.frozen,
    'kava/krasia-sampanies': D.drinks,
    'kava/mpires-milites': D.drinks,
    'kava/pota': D.drinks,
    'mpiskota-sokolates-zacharodi/mpiskota': D.snacks,
    'mpiskota-sokolates-zacharodi/pastelia-mantolata-loykoymia': D.snacks,
    'mpiskota-sokolates-zacharodi/sokolates': D.snacks,
    'mpiskota-sokolates-zacharodi/tsichles-karameles-gleifitzoyria': D.snacks,
    'orektika-delicatessen/chalvades': D.snacks,
    'orektika-delicatessen/elies': D.pantry,
    'orektika-delicatessen/kapnista-psaria': D.meat,
    'orektika-delicatessen/psaria-pasta-se-ladi': D.meat,
    'orektika-delicatessen/salates-aloifes': D.deli,
    'orektika-delicatessen/toyrsia-liastes-tomates': D.pantry,
    'trofes-eidi-gia-katoikidia/trofes-eidi-gia-gates': D.pets,
    'trofes-eidi-gia-katoikidia/trofes-eidi-gia-skyloys': D.pets,
    'trofima-pantopoleioy/aleyria-simigdalia': D.pantry,
    'trofima-pantopoleioy/ketsap-moystardes-magionezes-etoimes-saltses': D.pantry,
    'trofima-pantopoleioy/konserves-kompostes': D.canned,
    'trofima-pantopoleioy/ladia-lipi': D.pantry,
    'trofima-pantopoleioy/meigmata-gia-zele-glyka': D.pantry,
    'trofima-pantopoleioy/mpacharika-alatia-xidia-zomoi': D.pantry,
    'trofima-pantopoleioy/ntomatika': D.canned,
    'trofima-pantopoleioy/ospria': D.pantry,
    'trofima-pantopoleioy/poyredes-soypes-noodles': D.pantry,
    'trofima-pantopoleioy/ryzia': D.pantry,
    'trofima-pantopoleioy/sitari-kinoa-sogia-alla-dimitriaka': D.pantry,
    'trofima-pantopoleioy/ylika-mageirikis-zacharoplastikis': D.pantry,
    'trofima-pantopoleioy/zachari-ypokatastata-zacharis': D.pantry,
    'trofima-pantopoleioy/zymarika': D.pantry,
    'turokomika-futika-anapliromata/feta-leyka-tyria': D.cheese,
    'turokomika-futika-anapliromata/futika-anapliromata': D.cheese,
    'turokomika-futika-anapliromata/imisklira-tyria': D.cheese,
    'turokomika-futika-anapliromata/malaka-tyria': D.cheese,
    'turokomika-futika-anapliromata/sklira-tyria': D.cheese,
    'turokomika-futika-anapliromata/tyria-aleifomena-mini-tyrakia': D.cheese,
    'vrefikes-paidikes-trofes/vrefika-paidika-galata': D.baby,
    'vrefikes-paidikes-trofes/vrefika-paidika-snak': D.baby,
    'vrefikes-paidikes-trofes/vrefikes-paidikes-kremes': D.baby,
    'xiroi-karpoi-snak/patatakia-garidakia-alla-snak': D.snacks,
    'xiroi-karpoi-snak/xiroi-karpoi-apoxiramena-froyta': D.snacks,
  },

  ab: {
    // Known-but-mixed → keyword split (coffee + chocolate + gum in one bucket)
    'Πρωινό - snacking & ροφήματα': null,
    'Κατεψυγμένα τρόφιμα': D.frozen,
    'Βασικά τυποποιημένα τρόφιμα': D.pantry,
    'Για κατοικίδια': D.pets,
    'Άρτος Ζαχαροπλαστείο': D.bakery,
    'Γαλακτοκομικά, Φυτικά Ροφήματα & Είδη Ψυγείου': D.dairy,
    'Φρέσκο Κρέας & Ψάρια': D.meat,
    'Οπωροπωλείο': D.fruit,
    'Τυριά, Φυτικά Αναπληρώματα & Αλλαντικά': D.cheese,
    'Κάβα, αναψυκτικά, νερά, ξηροί καρποί': D.drinks,
    'Καθαριστικά - Χαρτικά & είδη σπιτιού': D.home,
    'Έτοιμα Γεύματα': D.deli, // chilled sushi/ready-to-eat counter
    'Όλα για το μωρό': D.baby,
    'Είδη προσωπικής περιποίησης': D.personal,
  },
};
